artifact_uri: /Users/mohitrohda/skill/Sign_language_detection/runs/mlflow/678747765835408496/0661a61f7df14814a48a3d2cea9bba8c/artifacts
end_time: 1790948514929
entry_point_name: ''
experiment_id: '678747765835408496'
lifecycle_stage: active
run_id: 0661a61f7df14814a48a3d2cea9bba8c
run_name: train-3
source_name: ''
source_type: 4
source_version: ''
start_time: 1790947975045
status: 3
tags: []
user_id: mohitrohda
